# Generated by Django 5.0.1 on 2024-04-22 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pollApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='voice',
            new_name='votes',
        ),
    ]
